version: 2.1

workflows:
  setup-minikube:
    jobs:
      - setup-minikube

jobs:
  setup-minikube:
    machine:
      image: circleci/classic:201808-01
      docker_layer_caching: true

    environment:
      K8S_VERSION: v1.12.0
      KUBECONFIG: /home/circleci/.kube/config
      MINIKUBE_VERSION: v0.31.0
      MINIKUBE_WANTUPDATENOTIFICATION: false
      MINIKUBE_WANTREPORTERRORPROMPT: false
      MINIKUBE_HOME: /home/circleci
      CHANGE_MINIKUBE_NONE_USER: true
    
    steps:
      - checkout
      - run:
          name: Install KinD
          command: |
            curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/0.0.1/kind-linux-amd64
            chmod +x kind
            sudo mv kind /usr/local/bin/
      - run:
          name: Create Kubernetes Cluster
          command: |
            kind create cluster
      - run:
          name: Install kubectl
          command: |
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/kubectl
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
      - run:
          name: Run Tests
          command: |
            export KUBECONFIG="$(kind get kubeconfig-path)"
            kubectl cluster-info
            kubectl get pods --all-namespaces
      - run:
          name: Setup kubeconfig ENV for Chaos Action
          command: |
            echo ::set-env name=KUBE_CONFIG_DATA::$(base64 -w 0 ${HOME}/.kube/config)
            cat ${KUBE_CONFIG_DATA}
      - run:
          name: Deploying a sample application (NGINX)
          command: |
            kubectl apply -f https://raw.githubusercontent.com/mayadata-io/chaos-ci-lib/master/app/nginx.yml
            sleep 30
      - run:
          name: Running pod-delete
          command: |
            echo "export INSTALL_LITMUS=true" >> $BASH_ENV
            echo "export EXPERIMENT_NAME=pod-delete" >> $BASH_ENV
            echo "export EXPERIMENT_IMAGE=litmuschaos/ansible-runner" >> $BASH_ENV
            echo "export EXPERIMENT_IMAGE_TAG=ci" >> $BASH_ENV
            echo "export IMAGE_PULL_POLICY=IfNotPresent" >> $BASH_ENV
            echo "export LITMUS_CLEANUP=true" >> $BASH_ENV
            source $BASH_ENV
            sleep 30
            docker run litmuschaos/chaos-ci-lib entrypoint="./pod-delete"
