name: Pod-Delete-CI-Workflow
on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
  push:
    branches: [master]

jobs:
  Our-Chaos-Action:
    runs-on: ubuntu-18.04
    env:
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    steps:

      - uses: actions/checkout@master

      - name: Installing Prerequisites (K3S Cluster)
        run: |
          curl -sfL https://get.k3s.io | sh -s - --docker --write-kubeconfig-mode 664
          kubectl wait node --all --for condition=ready --timeout=90s
          kubectl get nodes

      - name: Deploy a sample application for chaos injection
        run: |
          kubectl apply -f https://raw.githubusercontent.com/litmuschaos/chaos-ci-lib/master/app/nginx.yml
          sleep 30

      - name: Setting up kubeconfig ENV for Github Chaos Action
        run: echo ::set-env name=KUBE_CONFIG_DATA::$(base64 -w 0 ~/.kube/config)
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Setup Litmus
        uses: litmuschaos/github-chaos-actions@v0.3.1
        env:
          INSTALL_LITMUS: true

      - name: Running Litmus pod delete chaos experiment
        uses: litmuschaos/github-chaos-actions@v0.3.1
        env:
          APP_NS: default
          APP_LABEL: run=nginx
          APP_KIND: deployment
          EXPERIMENT_NAME: pod-delete
          EXPERIMENT_IMAGE: litmuschaos/go-runner
          EXPERIMENT_IMAGE_TAG: ci
          IMAGE_PULL_POLICY: Always
          JOB_CLEANUP_POLICY: delete

      - name: Uninstall Litmus
        uses: litmuschaos/github-chaos-actions@v0.3.1
        env:
          LITMUS_CLEANUP: true

      - name: Deleting K3S cluster
        if: always()
        run: /usr/local/bin/k3s-uninstall.sh
